# Generated by Django 2.0.4 on 2018-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(max_length=30),
        ),
    ]
